{{- if .Values.gateway.enabled -}}
{{- $fullName := include "dhis2-core-helm.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dhis2-core-helm.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: {{ .Values.gateway.hostname | quote }}
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.gateway.hostname | quote }}
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.tls.secretName | default (printf "%s-%s-tls" $fullName (replace "." "-" .Values.gateway.hostname)) }}
        options:
          {{- if .Values.gateway.tls.certIssuer }}
          cert-manager:
            clusterIssuer: {{ .Values.gateway.tls.certIssuer | quote }}
          {{- end }}
    {{- end }}
{{- end }}
