{{- if .Values.gateway.enabled -}}
{{- $fullName := include "dhis2-core-helm.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dhis2-core-helm.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ $fullName }}
      sectionName: http
    {{- if .Values.gateway.tls.enabled }}
    - name: {{ $fullName }}
      sectionName: https
    {{- end }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.routes.main.path }}
      backendRefs:
        - name: {{ $fullName }}{{ if .Values.keda.enabled }}-keda-proxy{{ end }}
          port: {{ .Values.gateway.routes.main.servicePort }}
{{- end }}
